SPLIT_KEYBOARD = yes
RGBLIGHT_ENABLE = no

ifdef WITH_JOYSTICK
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog # or 'digital'
POINTING_DEVICE_ENABLE = yes
OPT_DEFS += -DWITH_JOYSTICK
endif

ifdef APPLE_EXTENDED
$(warning LUAKH CONFIGURING FOR APPLE_EXTENDED KEYBOARD)
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog # or 'digital'
POINTING_DEVICE_ENABLE = yes
OPT_DEFS += -DAPPLE_EXTENDED -DWITH_JOYSTICK
endif
