SPLIT_KEYBOARD = yes
RGBLIGHT_ENABLE = no

ifdef WITH_JOYSTICK
JOYSTICK_ENABLE = analog
POINTING_DEVICE_ENABLE = yes
OPT_DEFS += -DWITH_JOYSTICK
endif

ifdef APPLE_EXTENDED
$(warning LUAKH CONFIGURING FOR APPLE_EXTENDED KEYBOARD)
POINTING_DEVICE_ENABLE = yes
JOYSTICK_ENABLE = analog
OPT_DEFS += -DAPPLE_EXTENDED -DWITH_JOYSTICK
endif
